import sys
from pathlib import Path

from pyspark.sql import SparkSession
from pyspark.sql import functions as F
from pyspark.sql.window import Window


# ============================================================================
# CONFIGURATION
# ============================================================================

PROJECT_ROOT = Path(__file__).resolve().parent.parent

# ---------------------------------------------------------------------------
# SP2 PARQUET INPUT
# ---------------------------------------------------------------------------
# SP3 reads the verified Parquet generated by SP2.
# SP3 does NOT call run_sp2().
# ---------------------------------------------------------------------------

SP2_OUTPUT_DIR = (
    PROJECT_ROOT
    / "data"
    / "processed"
    / "sp2_clean"
)

# ---------------------------------------------------------------------------
# SP3 PARQUET OUTPUT
# ---------------------------------------------------------------------------

SP3_OUTPUT_DIR = (
    PROJECT_ROOT
    / "data"
    / "processed"
    / "sp3_hourly_grid"
)

# ---------------------------------------------------------------------------
# ASSIGNMENT EXPECTATIONS
# ---------------------------------------------------------------------------

EXPECTED_DAYS = 7
EXPECTED_HOURS_PER_DAY = 24
MAX_GRIDS = 10000

EXPECTED_HOURLY_TIMESTAMPS = (
    EXPECTED_DAYS * EXPECTED_HOURS_PER_DAY
)

EXPECTED_MAX_ROWS = (
    EXPECTED_DAYS
    * EXPECTED_HOURS_PER_DAY
    * MAX_GRIDS
)


# ============================================================================
# HEADER
# ============================================================================

def print_header(title):

    print()
    print("=" * 75)
    print(title)
    print("=" * 75)


# ============================================================================
# SPARK SESSION
# ============================================================================

def create_spark_session():

    print()
    print("[1] Creating Spark session...")
    print("-" * 75)

    spark = (
        SparkSession.builder
        .appName("SP3-Milan-Telecom-Aggregation")
        .master("local[*]")

        # ---------------------------------------------------------------
        # Memory / execution configuration
        # ---------------------------------------------------------------

        .config(
            "spark.sql.shuffle.partitions",
            "15"
        )

        .config(
            "spark.sql.session.timeZone",
            "UTC"
        )

        .config(
            "spark.sql.adaptive.enabled",
            "true"
        )

        .config(
            "spark.sql.adaptive.coalescePartitions.enabled",
            "true"
        )

        .config(
            "spark.sql.adaptive.skewJoin.enabled",
            "true"
        )

        .config(
            "spark.sql.debug.maxToStringFields",
            "200"
        )

        .config(
            "spark.speculation",
            "false"
        )

        .getOrCreate()
    )

    spark.sparkContext.setLogLevel("WARN")

    print("Spark session created successfully")
    print(f"Spark version: {spark.version}")

    return spark


# ============================================================================
# DISCOVER SP2 PARQUET
# ============================================================================

def validate_sp2_parquet_exists():

    print()
    print("[2] Checking SP2 Parquet input...")
    print("-" * 75)

    if not SP2_OUTPUT_DIR.exists():

        raise FileNotFoundError(
            "SP2 Parquet output directory does not exist:\n"
            f"{SP2_OUTPUT_DIR}\n\n"
            "Run SP2 first."
        )

    parquet_files = sorted(
        [
            path
            for path in SP2_OUTPUT_DIR.rglob("*")
            if (
                path.is_file()
                and path.suffix.lower() == ".parquet"
            )
        ]
    )

    if not parquet_files:

        raise FileNotFoundError(
            "No Parquet files found in SP2 output directory:\n"
            f"{SP2_OUTPUT_DIR}"
        )

    print(
        f"SP2 Parquet directory : {SP2_OUTPUT_DIR}"
    )

    print(
        f"Parquet files found   : {len(parquet_files)}"
    )

    for file in parquet_files[:10]:
        print(f"  - {file.name}")

    if len(parquet_files) > 10:
        print(
            f"  ... and "
            f"{len(parquet_files) - 10} more"
        )

    print()
    print("SP2 Parquet input: PASS")

    return parquet_files


# ============================================================================
# READ SP2 PARQUET
# ============================================================================

def read_sp2_parquet(spark):

    print()
    print("[3] Reading SP2 Parquet output...")
    print("-" * 75)

    df = (
        spark.read
        .parquet(str(SP2_OUTPUT_DIR))
    )

    sp2_rows = df.count()

    print(
        f"SP2 Parquet rows    : {sp2_rows:,}"
    )

    print(
        f"SP2 columns         : {len(df.columns)}"
    )

    print()
    print("SP2 Parquet schema:")

    df.printSchema()

    return df, sp2_rows


# ============================================================================
# SP2 INPUT VALIDATION
# ============================================================================

def validate_sp2_input(clean_df):

    print()
    print("[4] Validating SP2 Parquet schema received by SP3...")
    print("-" * 75)

    required_columns = [

        "timestamp",
        "date",
        "hour",
        "day_of_week",

        "grid_id",
        "country_code",

        "sms_in",
        "sms_out",

        "call_in",
        "call_out",

        "internet_activity",

        "total_sms",
        "total_calls",
        "total_activity",
    ]

    missing_columns = [
        column
        for column in required_columns
        if column not in clean_df.columns
    ]

    if missing_columns:

        raise ValueError(
            "SP2 Parquet is missing required columns:\n"
            + "\n".join(
                f"  - {column}"
                for column in missing_columns
            )
        )

    print("Status: PASS")

    print(
        "SP2 Parquet contains all required columns."
    )

    print()
    print("SP2 grain:")

    print(
        "timestamp + grid_id + country_code"
    )


# ============================================================================
# VALIDATE SP2 GRAIN
# ============================================================================

def validate_sp2_grain(clean_df):

    print()
    print("[5] Validating SP2 input grain...")
    print("-" * 75)

    total_rows = clean_df.count()

    distinct_grain_rows = (
        clean_df
        .select(
            "timestamp",
            "grid_id",
            "country_code"
        )
        .distinct()
        .count()
    )

    duplicate_rows = (
        total_rows - distinct_grain_rows
    )

    print(
        f"SP2 total rows              : "
        f"{total_rows:,}"
    )

    print(
        f"Distinct SP2 grain rows     : "
        f"{distinct_grain_rows:,}"
    )

    print(
        f"Duplicate grain rows        : "
        f"{duplicate_rows:,}"
    )

    if duplicate_rows != 0:

        raise ValueError(
            "SP2 input grain validation failed. "
            "Duplicate records exist at "
            "(timestamp, grid_id, country_code)."
        )

    print()
    print(
        "SP2 grain validation: PASS"
    )


# ============================================================================
# SP3 AGGREGATION
# ============================================================================

def aggregate_country_codes(clean_df):

    print()
    print("[6] Aggregating country-code records...")
    print("-" * 75)

    print()
    print("SP3 transformation:")

    print(
        "BEFORE : timestamp + grid_id + country_code"
    )

    print(
        "AFTER  : timestamp + grid_id"
    )

    print()
    print("Aggregation rules:")

    print("  sms_in            -> SUM")
    print("  sms_out           -> SUM")
    print("  call_in           -> SUM")
    print("  call_out          -> SUM")
    print("  internet_activity -> SUM")

    print()
    print(
        "Executing groupBy(timestamp, grid_id)..."
    )

    # ------------------------------------------------------------------------
    # ACTUAL SP3 TRANSFORMATION
    # ------------------------------------------------------------------------

    hourly_grid_summary = (
        clean_df

        .groupBy(
            "timestamp",
            "grid_id"
        )

        .agg(

            F.round(
                F.sum("sms_in"),
                4
            ).alias("sms_in"),

            F.round(
                F.sum("sms_out"),
                4
            ).alias("sms_out"),

            F.round(
                F.sum("call_in"),
                4
            ).alias("call_in"),

            F.round(
                F.sum("call_out"),
                4
            ).alias("call_out"),

            F.round(
                F.sum("internet_activity"),
                4
            ).alias("internet_activity")
        )
    )

    return hourly_grid_summary


# ============================================================================
# RECREATE TEMPORAL FIELDS
# ============================================================================

def add_temporal_fields(df):

    print()
    print("[7] Preparing hourly grid temporal fields...")
    print("-" * 75)

    df = (
        df

        .withColumn(
            "date",
            F.to_date(
                F.col("timestamp")
            )
        )

        .withColumn(
            "hour",
            F.hour(
                F.col("timestamp")
            )
        )

        .withColumn(
            "day_of_week",
            F.dayofweek(
                F.col("timestamp")
            )
        )
    )

    print(
        "date, hour and day_of_week recreated "
        "from timestamp."
    )

    return df


# ============================================================================
# CREATE AGGREGATED TOTALS
# ============================================================================

def create_aggregated_totals(df):

    print()
    print("[8] Creating aggregated activity totals...")
    print("-" * 75)

    df = (

        df

        .withColumn(
            "total_sms",
            F.round(
                F.col("sms_in")
                + F.col("sms_out"),
                4
            )
        )

        .withColumn(
            "total_calls",
            F.round(
                F.col("call_in")
                + F.col("call_out"),
                4
            )
        )

        .withColumn(
            "total_activity",
            F.round(
                F.col("total_sms")
                + F.col("total_calls")
                + F.col("internet_activity"),
                4
            )
        )
    )

    print(
        "total_sms = sms_in + sms_out"
    )

    print(
        "total_calls = call_in + call_out"
    )

    print(
        "total_activity = total_sms + "
        "total_calls + internet_activity"
    )

    return df


# ============================================================================
# FINAL SCHEMA
# ============================================================================

def prepare_final_schema(df):

    print()
    print("[9] Preparing final SP3 schema...")
    print("-" * 75)

    final_columns = [

        "timestamp",
        "date",
        "hour",
        "day_of_week",

        "grid_id",

        "sms_in",
        "sms_out",

        "call_in",
        "call_out",

        "internet_activity",

        "total_sms",
        "total_calls",
        "total_activity",
    ]

    df = df.select(
        *final_columns
    )

    print()
    print("Final SP3 columns:")

    for column in df.columns:
        print(f"  - {column}")

    return df


# ============================================================================
# ROW COUNT VALIDATION
# ============================================================================

def validate_row_count(
    sp2_rows,
    sp3_rows
):

    print()
    print("[10] Validating SP3 row count...")
    print("-" * 75)

    print(
        f"SP2 input rows : {sp2_rows:,}"
    )

    print(
        f"SP3 output rows: {sp3_rows:,}"
    )

    if sp3_rows >= sp2_rows:

        raise ValueError(
            "SP3 row-count validation failed. "
            "Aggregated row count must be smaller "
            "than SP2 row count."
        )

    print(
        f"Rows reduced   : "
        f"{sp2_rows - sp3_rows:,}"
    )

    print(
        "Row-count reduction: PASS"
    )


# ============================================================================
# MAXIMUM ROW COUNT
# ============================================================================

def validate_max_rows(sp3_rows):

    print()
    print("[11] Validating assignment row-count bound...")
    print("-" * 75)

    print(
        f"Maximum allowed rows: "
        f"{EXPECTED_MAX_ROWS:,}"
    )

    print(
        f"Actual SP3 rows     : "
        f"{sp3_rows:,}"
    )

    if sp3_rows > EXPECTED_MAX_ROWS:

        raise ValueError(
            "SP3 maximum row-count validation failed. "
            f"{sp3_rows:,} > {EXPECTED_MAX_ROWS:,}"
        )

    print(
        "Maximum row-count validation: PASS"
    )


# ============================================================================
# DUPLICATE VALIDATION
# ============================================================================

def validate_no_duplicates(df):

    print()
    print(
        "[12] Asserting ZERO duplicates on "
        "grid_id + timestamp..."
    )
    print("-" * 75)

    duplicate_groups = (

        df

        .groupBy(
            "grid_id",
            "timestamp"
        )

        .count()

        .filter(
            F.col("count") > 1
        )
    )

    duplicate_count = (
        duplicate_groups.count()
    )

    print(
        f"Duplicate groups: "
        f"{duplicate_count:,}"
    )

    if duplicate_count != 0:

        raise ValueError(
            "CRITICAL SP3 VALIDATION FAILED. "
            "Duplicate (grid_id, timestamp) "
            "records found."
        )

    print(
        "Duplicate assertion: PASS"
    )

    print(
        "ZERO duplicates found."
    )

    return duplicate_count


# ============================================================================
# COUNTRY CODE REMOVAL VALIDATION
# ============================================================================

def validate_country_code_removed(df):

    print()
    print("[13] Validating country_code removal...")
    print("-" * 75)

    if "country_code" in df.columns:

        raise ValueError(
            "country_code must NOT appear "
            "in final SP3 output."
        )

    print(
        "country_code present in output: NO"
    )

    print(
        "Country-code removal: PASS"
    )


# ============================================================================
# TEMPORAL VALIDATION
# ============================================================================
#
# IMPORTANT:
#
# The dataset has:
#
#   2013-11-01 05:30:00
#   through
#   2013-11-08 04:30:00
#
# This spans 8 calendar dates, but represents exactly:
#
#   7 days × 24 hours = 168 hourly timestamps
#
# Therefore we DO NOT require:
#
#   distinct_dates == 7
#
# Instead we validate:
#
#   1. 24 distinct hour values
#   2. 168 distinct timestamps
#   3. timestamps are exactly one hour apart
#
# ============================================================================

def validate_temporal_coverage(df):

    print()
    print("[14] Validating hourly timestamp coverage...")
    print("-" * 75)

    # ------------------------------------------------------------------------
    # DISTINCT TIMESTAMPS
    # ------------------------------------------------------------------------

    distinct_timestamps = (
        df
        .select("timestamp")
        .distinct()
        .count()
    )

    # ------------------------------------------------------------------------
    # DISTINCT DATES
    # ------------------------------------------------------------------------

    distinct_dates = (
        df
        .select("date")
        .distinct()
        .count()
    )

    # ------------------------------------------------------------------------
    # DISTINCT HOURS
    # ------------------------------------------------------------------------

    distinct_hours = (
        df
        .select("hour")
        .distinct()
        .count()
    )

    # ------------------------------------------------------------------------
    # MINIMUM / MAXIMUM TIMESTAMP
    # ------------------------------------------------------------------------

    timestamp_range = (
        df
        .select(
            F.min("timestamp").alias("min_timestamp"),
            F.max("timestamp").alias("max_timestamp")
        )
        .first()
    )

    min_timestamp = (
        timestamp_range["min_timestamp"]
    )

    max_timestamp = (
        timestamp_range["max_timestamp"]
    )

    # ------------------------------------------------------------------------
    # PRINT RESULTS
    # ------------------------------------------------------------------------

    print(
        f"Minimum timestamp        : "
        f"{min_timestamp}"
    )

    print(
        f"Maximum timestamp        : "
        f"{max_timestamp}"
    )

    print(
        f"Distinct calendar dates  : "
        f"{distinct_dates}"
    )

    print(
        f"Distinct hours           : "
        f"{distinct_hours}"
    )

    print(
        f"Distinct timestamps      : "
        f"{distinct_timestamps}"
    )

    print(
        f"Expected hourly timestamps: "
        f"{EXPECTED_HOURLY_TIMESTAMPS}"
    )

    # ------------------------------------------------------------------------
    # VALIDATE TIMESTAMP EXISTENCE
    # ------------------------------------------------------------------------

    if min_timestamp is None or max_timestamp is None:

        raise ValueError(
            "Timestamp validation failed. "
            "Minimum or maximum timestamp is NULL."
        )

    # ------------------------------------------------------------------------
    # VALIDATE 24 HOURS
    # ------------------------------------------------------------------------

    if distinct_hours != EXPECTED_HOURS_PER_DAY:

        raise ValueError(
            "Expected all 24 hours "
            f"but found {distinct_hours}."
        )

    # ------------------------------------------------------------------------
    # VALIDATE 168 HOURLY TIMESTAMPS
    # ------------------------------------------------------------------------

    if distinct_timestamps != EXPECTED_HOURLY_TIMESTAMPS:

        raise ValueError(
            "Expected "
            f"{EXPECTED_HOURLY_TIMESTAMPS} distinct hourly timestamps "
            f"but found {distinct_timestamps}."
        )

    # ------------------------------------------------------------------------
    # VALIDATE HOURLY INTERVALS
    #
    # IMPORTANT:
    #
    # We check distinct timestamps only.
    # Otherwise every grid would appear in the window calculation.
    # ------------------------------------------------------------------------

    window_spec = (
        Window
        .orderBy("timestamp")
    )

    timestamp_gaps = (

        df

        .select("timestamp")

        .distinct()

        .withColumn(
            "previous_timestamp",
            F.lag("timestamp").over(
                window_spec
            )
        )

        .withColumn(
            "diff_seconds",
            F.col("timestamp").cast("long")
            -
            F.col("previous_timestamp").cast("long")
        )

        .filter(
            F.col("previous_timestamp").isNotNull()
        )

        .filter(
            F.col("diff_seconds") != 3600
        )

        .count()
    )

    print(
        f"Non-hourly timestamp gaps : "
        f"{timestamp_gaps}"
    )

    if timestamp_gaps != 0:

        raise ValueError(
            "Timestamp coverage validation failed. "
            "Non-hourly timestamp gaps detected."
        )

    # ------------------------------------------------------------------------
    # PASS
    # ------------------------------------------------------------------------

    print()
    print(
        "Hourly timestamp count validation: PASS"
    )

    print(
        "24-hour coverage validation: PASS"
    )

    print(
        "Hourly interval validation: PASS"
    )

    print(
        "Temporal coverage validation: PASS"
    )


# ============================================================================
# FINAL NULL VALIDATION
# ============================================================================

def validate_no_nulls(df):

    print()
    print("[15] Final NULL validation...")
    print("-" * 75)

    null_failure = False

    for column in df.columns:

        null_count = (

            df

            .filter(
                F.col(column).isNull()
            )

            .count()
        )

        print(
            f"{column:<20}: "
            f"{null_count:,}"
        )

        if null_count != 0:

            null_failure = True

    if null_failure:

        raise ValueError(
            "Final SP3 NULL validation failed."
        )

    print()
    print(
        "NULL validation: PASS"
    )


# ============================================================================
# FINAL NEGATIVE VALIDATION
# ============================================================================

def validate_no_negative_values(df):

    print()
    print("[16] Final negative activity validation...")
    print("-" * 75)

    activity_columns = [

        "sms_in",
        "sms_out",

        "call_in",
        "call_out",

        "internet_activity",
    ]

    failure = False

    for column in activity_columns:

        negative_count = (

            df

            .filter(
                F.col(column) < 0
            )

            .count()
        )

        print(
            f"{column:<20}: "
            f"{negative_count:,} negative values"
        )

        if negative_count != 0:

            failure = True

    if failure:

        raise ValueError(
            "Negative activity values "
            "found after SP3 aggregation."
        )

    print()
    print(
        "Negative activity validation: PASS"
    )


# ============================================================================
# HAND CHECK
# ============================================================================

def perform_hand_check(
    clean_df,
    hourly_grid_summary
):

    print()
    print(
        "[17] Hand-checking one grid and timestamp..."
    )
    print("-" * 75)

    sample_key = (

        clean_df

        .select(
            "grid_id",
            "timestamp"
        )

        .orderBy(
            "timestamp",
            "grid_id"
        )

        .first()
    )

    if sample_key is None:

        raise ValueError(
            "Unable to find sample "
            "grid/timestamp."
        )

    sample_grid = (
        sample_key["grid_id"]
    )

    sample_timestamp = (
        sample_key["timestamp"]
    )

    print(
        f"Selected grid_id  : "
        f"{sample_grid}"
    )

    print(
        f"Selected timestamp : "
        f"{sample_timestamp}"
    )

    # ------------------------------------------------------------------------
    # BEFORE SP3
    # ------------------------------------------------------------------------

    before = (

        clean_df

        .filter(

            (F.col("grid_id") == sample_grid)

            & (

                F.col("timestamp")
                == sample_timestamp
            )
        )

        .agg(

            F.sum("sms_in")
            .alias("sms_in"),

            F.sum("sms_out")
            .alias("sms_out"),

            F.sum("call_in")
            .alias("call_in"),

            F.sum("call_out")
            .alias("call_out"),

            F.sum(
                "internet_activity"
            )
            .alias("internet_activity")
        )

        .first()
    )

    # ------------------------------------------------------------------------
    # AFTER SP3
    # ------------------------------------------------------------------------

    after = (

        hourly_grid_summary

        .filter(

            (F.col("grid_id") == sample_grid)

            & (

                F.col("timestamp")
                == sample_timestamp
            )
        )

        .first()
    )

    if after is None:

        raise ValueError(
            "Hand-check failed. "
            "Aggregated record not found."
        )

    def rounded(value):

        if value is None:
            return 0.0

        return round(
            float(value),
            4
        )

    checks = [

        (
            "sms_in",
            rounded(
                before["sms_in"]
            ),
            rounded(
                after["sms_in"]
            )
        ),

        (
            "sms_out",
            rounded(
                before["sms_out"]
            ),
            rounded(
                after["sms_out"]
            )
        ),

        (
            "call_in",
            rounded(
                before["call_in"]
            ),
            rounded(
                after["call_in"]
            )
        ),

        (
            "call_out",
            rounded(
                before["call_out"]
            ),
            rounded(
                after["call_out"]
            )
        ),

        (
            "internet_activity",
            rounded(
                before["internet_activity"]
            ),
            rounded(
                after["internet_activity"]
            )
        ),
    ]

    print()
    print("Hand-check comparison:")

    hand_check_pass = True

    for (
        name,
        expected,
        actual
    ) in checks:

        passed = (
            expected == actual
        )

        print(
            f"  {name:<20} "
            f"expected={expected:<15} "
            f"actual={actual:<15} "
            f"{'PASS' if passed else 'FAIL'}"
        )

        if not passed:

            hand_check_pass = False

    if not hand_check_pass:

        raise ValueError(
            "Hand-check failed. "
            "SP3 aggregation does not match "
            "SP2 country-code sums."
        )

    print()
    print(
        "Hand-check: PASS"
    )


# ============================================================================
# SAMPLE OUTPUT
# ============================================================================

def show_sample(df):

    print()
    print(
        "[18] Sample SP3 hourly_grid_summary records..."
    )
    print("-" * 75)

    (
        df

        .orderBy(
            "timestamp",
            "grid_id"
        )

        .show(
            10,
            truncate=False
        )
    )


# ============================================================================
# ACTIVITY SUMMARY
# ============================================================================

def show_activity_summary(df):

    print()
    print("[19] SP3 activity summary...")
    print("-" * 75)

    summary_columns = [

        "sms_in",
        "sms_out",

        "call_in",
        "call_out",

        "internet_activity",

        "total_sms",
        "total_calls",
        "total_activity",
    ]

    (
        df

        .select(
            *summary_columns
        )

        .summary(
            "count",
            "mean",
            "min",
            "50%",
            "max"
        )

        .show(
            truncate=False
        )
    )


# ============================================================================
# WRITE SP3 PARQUET
# ============================================================================

def write_sp3_output(df):

    print()
    print("[20] Writing SP3 output to Parquet...")
    print("-" * 75)

    print(
        "Output location:"
    )

    print(
        SP3_OUTPUT_DIR
    )

    # ------------------------------------------------------------------------
    # Remove previous SP3 output if it exists.
    # Spark overwrite will replace the existing contents.
    # ------------------------------------------------------------------------

    if SP3_OUTPUT_DIR.exists():

        print()
        print(
            "Previous SP3 output directory exists."
        )

        print(
            "Spark will overwrite the previous output."
        )

    (
        df

        .write

        .mode("overwrite")

        .option(
            "compression",
            "snappy"
        )

        .parquet(
            str(SP3_OUTPUT_DIR)
        )
    )

    print()
    print(
        "SP3 Parquet write: PASS"
    )

    return SP3_OUTPUT_DIR


# ============================================================================
# VERIFY SP3 PARQUET
# ============================================================================

def verify_sp3_parquet(
    spark,
    expected_rows
):

    print()
    print("[21] Verifying SP3 Parquet output...")
    print("-" * 75)

    if not SP3_OUTPUT_DIR.exists():

        raise FileNotFoundError(
            "SP3 Parquet output was not created:\n"
            f"{SP3_OUTPUT_DIR}"
        )

    parquet_files = sorted(

        [
            path
            for path in SP3_OUTPUT_DIR.rglob("*")

            if (
                path.is_file()
                and path.suffix.lower() == ".parquet"
            )
        ]
    )

    print(
        f"Parquet files found: "
        f"{len(parquet_files)}"
    )

    if not parquet_files:

        raise ValueError(
            "No Parquet files found "
            "in SP3 output."
        )

    verified_df = (

        spark.read

        .parquet(
            str(SP3_OUTPUT_DIR)
        )
    )

    actual_rows = (
        verified_df.count()
    )

    print(
        f"Rows read back from Parquet: "
        f"{actual_rows:,}"
    )

    if actual_rows != expected_rows:

        raise ValueError(

            "SP3 Parquet row-count "
            "verification failed. "

            f"Expected {expected_rows:,}, "
            f"found {actual_rows:,}."
        )

    print()
    print(
        "Verified SP3 Parquet schema:"
    )

    verified_df.printSchema()

    # ------------------------------------------------------------------------
    # Verify country_code is absent
    # ------------------------------------------------------------------------

    if "country_code" in verified_df.columns:

        raise ValueError(
            "country_code exists in "
            "SP3 Parquet output."
        )

    # ------------------------------------------------------------------------
    # Verify required columns
    # ------------------------------------------------------------------------

    expected_columns = [

        "timestamp",
        "date",
        "hour",
        "day_of_week",
        "grid_id",

        "sms_in",
        "sms_out",

        "call_in",
        "call_out",

        "internet_activity",

        "total_sms",
        "total_calls",
        "total_activity",
    ]

    if verified_df.columns != expected_columns:

        raise ValueError(

            "SP3 Parquet schema mismatch.\n"

            f"Expected: {expected_columns}\n"

            f"Found: {verified_df.columns}"
        )

    print()
    print(
        "SP3 Parquet verification: PASS"
    )

    return verified_df


# ============================================================================
# CORE SP3 TRANSFORMATION
# ============================================================================
#
# IMPORTANT:
#
# SP3:
#
#     READ SP2 PARQUET
#          ↓
#     VALIDATE SP2
#          ↓
#     AGGREGATE COUNTRY CODES
#          ↓
#     CREATE HOURLY GRID SUMMARY
#          ↓
#     VALIDATE
#          ↓
#     WRITE SP3 PARQUET
#          ↓
#     VERIFY SP3 PARQUET
#
# SP3 DOES NOT:
#
#     - read raw CSV
#     - call run_sp2()
#     - clean raw data
#     - standardize raw columns
#
# Those are SP2 responsibilities.
#
# ============================================================================

def run_sp3(spark):

    print_header(
        "SP3 - MILAN TELECOM COUNTRY-CODE AGGREGATION"
    )

    # ========================================================================
    # SP2 PARQUET INPUT
    # ========================================================================

    validate_sp2_parquet_exists()

    clean_df, sp2_rows = (
        read_sp2_parquet(
            spark
        )
    )

    # ========================================================================
    # VALIDATE SP2
    # ========================================================================

    validate_sp2_input(
        clean_df
    )

    validate_sp2_grain(
        clean_df
    )

    print()
    print(
        f"SP2 Parquet rows received by SP3: "
        f"{sp2_rows:,}"
    )

    # ========================================================================
    # ACTUAL SP3 AGGREGATION
    # ========================================================================

    hourly_grid_summary = (
        aggregate_country_codes(
            clean_df
        )
    )

    # ========================================================================
    # TEMPORAL FIELDS
    # ========================================================================

    hourly_grid_summary = (
        add_temporal_fields(
            hourly_grid_summary
        )
    )

    # ========================================================================
    # TOTALS
    # ========================================================================

    hourly_grid_summary = (
        create_aggregated_totals(
            hourly_grid_summary
        )
    )

    # ========================================================================
    # FINAL SCHEMA
    # ========================================================================

    hourly_grid_summary = (
        prepare_final_schema(
            hourly_grid_summary
        )
    )

    # ========================================================================
    # VALIDATIONS
    # ========================================================================

    sp3_rows = (
        hourly_grid_summary.count()
    )

    validate_row_count(
        sp2_rows,
        sp3_rows
    )

    validate_max_rows(
        sp3_rows
    )

    duplicate_count = (
        validate_no_duplicates(
            hourly_grid_summary
        )
    )

    validate_country_code_removed(
        hourly_grid_summary
    )

    validate_temporal_coverage(
        hourly_grid_summary
    )

    validate_no_nulls(
        hourly_grid_summary
    )

    validate_no_negative_values(
        hourly_grid_summary
    )

    # ========================================================================
    # HAND CHECK
    # ========================================================================

    perform_hand_check(
        clean_df,
        hourly_grid_summary
    )

    # ========================================================================
    # DISPLAY
    # ========================================================================

    show_sample(
        hourly_grid_summary
    )

    show_activity_summary(
        hourly_grid_summary
    )

    # ========================================================================
    # WRITE PARQUET
    # ========================================================================

    write_sp3_output(
        hourly_grid_summary
    )

    # ========================================================================
    # VERIFY PARQUET
    # ========================================================================

    verified_df = (
        verify_sp3_parquet(
            spark,
            sp3_rows
        )
    )

    # ========================================================================
    # SUCCESS
    # ========================================================================

    print()
    print("=" * 75)
    print(
        "SP3 AGGREGATION COMPLETED SUCCESSFULLY"
    )
    print("=" * 75)

    print(
        f"SP2 input rows           : "
        f"{sp2_rows:,}"
    )

    print(
        f"SP3 output rows          : "
        f"{sp3_rows:,}"
    )

    print(
        f"Rows reduced             : "
        f"{sp2_rows - sp3_rows:,}"
    )

    print(
        f"Duplicate groups         : "
        f"{duplicate_count}"
    )

    print(
        f"Expected hourly timestamps: "
        f"{EXPECTED_HOURLY_TIMESTAMPS}"
    )

    print(
        f"Maximum allowed rows     : "
        f"{EXPECTED_MAX_ROWS:,}"
    )

    print(
        "Input source             : "
        "SP2 Parquet"
    )

    print(
        f"SP2 input location       : "
        f"{SP2_OUTPUT_DIR}"
    )

    print(
        "Aggregation grain        : "
        "timestamp + grid_id"
    )

    print(
        "country_code in output   : NO"
    )

    print(
        "Output format            : Parquet"
    )

    print(
        f"Output location          : "
        f"{SP3_OUTPUT_DIR}"
    )

    print(
        "Parquet verification     : PASS"
    )

    print(
        "Hand-check               : PASS"
    )

    print(
        "NULL validation          : PASS"
    )

    print(
        "Negative validation      : PASS"
    )

    print(
        "Temporal validation      : PASS"
    )

    print(
        "Status                   : SUCCESS"
    )

    print("=" * 75)

    # ------------------------------------------------------------------------
    # RETURN SP3 OUTPUT TO NEXT STAGE
    # ------------------------------------------------------------------------

    return verified_df


# ============================================================================
# MAIN
# ============================================================================

def main():

    spark = None

    try:

        spark = (
            create_spark_session()
        )

        hourly_grid_summary = (
            run_sp3(
                spark
            )
        )

        print()
        print(
            "SP3 DataFrame successfully returned."
        )

        print(
            "Output DataFrame: "
            "hourly_grid_summary"
        )

        print()
        print(
            "SP3 Parquet output is ready for SP4."
        )

        print(
            "SP3 output:"
        )

        print(
            SP3_OUTPUT_DIR
        )

    except Exception as exc:

        print()
        print("=" * 75)
        print(
            "SP3 FAILED"
        )
        print("=" * 75)

        print(
            f"Error type: "
            f"{type(exc).__name__}"
        )

        print(
            f"Error: "
            f"{exc}"
        )

        sys.exit(1)

    finally:

        if spark is not None:

            try:
                spark.stop()

            except Exception:
                pass


# ============================================================================
# ENTRY POINT
# ============================================================================

if __name__ == "__main__":

    main()