import os
import sys
import json
import math

# ============================================================
# WINDOWS PYTHON WORKER CONFIGURATION
# ============================================================

PYTHON_EXE = sys.executable

os.environ["PYSPARK_PYTHON"] = PYTHON_EXE
os.environ["PYSPARK_DRIVER_PYTHON"] = PYTHON_EXE

from pyspark.sql import SparkSession
from pyspark.sql import functions as F
from pyspark.sql.functions import broadcast


# ============================================================
# PATHS
# ============================================================

BASE_DIR = os.path.abspath(
    os.path.join(
        os.path.dirname(__file__),
        ".."
    )
)

# ------------------------------------------------------------
# SP3 PARQUET INPUT
# ------------------------------------------------------------
# SP4 directly reads the verified Parquet generated by SP3.
#
# SP4 DOES NOT:
#   - call run_sp3()
#   - rerun SP3
#   - read raw CSV
#   - perform SP3 aggregation
# ------------------------------------------------------------

SP3_OUTPUT_DIR = os.path.join(
    BASE_DIR,
    "data",
    "processed",
    "sp3_hourly_grid"
)

# ------------------------------------------------------------
# GEOJSON REFERENCE
# ------------------------------------------------------------

GEOJSON_PATH = os.environ.get(
    "MILANO_GEOJSON_PATH",
    os.path.join(
        BASE_DIR,
        "data",
        "reference",
        "milano-grid.geojson"
    )
)


# ============================================================
# REQUIRED SP3 COLUMNS
# ============================================================

REQUIRED_SP3_COLUMNS = [

    "timestamp",
    "date",
    "hour",
    "day_of_week",

    "grid_id",

    "sms_in",
    "sms_out",

    "call_in",
    "call_out",

    "internet_activity",

    "total_sms",
    "total_calls",
    "total_activity",
]


# ============================================================
# EXPECTATIONS
# ============================================================

EXPECTED_GRID_CELLS = 10000


# ============================================================
# SPARK SESSION
# ============================================================

def create_spark_session():

    print()
    print("[1] Creating Spark session...")
    print("-" * 75)

    spark = (
        SparkSession.builder

        .appName(
            "SP4-Milan-Telecom-Geospatial-Enrichment"
        )

        .master("local[*]")

        .config(
            "spark.sql.shuffle.partitions",
            "8"
        )

        .config(
            "spark.sql.adaptive.enabled",
            "true"
        )

        .config(
            "spark.sql.adaptive.coalescePartitions.enabled",
            "true"
        )

        .config(
            "spark.sql.autoBroadcastJoinThreshold",
            "50MB"
        )

        .config(
            "spark.sql.session.timeZone",
            "UTC"
        )

        .config(
            "spark.pyspark.python",
            PYTHON_EXE
        )

        .config(
            "spark.pyspark.driver.python",
            PYTHON_EXE
        )

        .config(
            "spark.python.worker.reuse",
            "true"
        )

        .getOrCreate()
    )

    spark.sparkContext.setLogLevel("WARN")

    print(
        "Spark session created successfully"
    )

    print(
        f"Spark version: {spark.version}"
    )

    print(
        f"Python executable: {PYTHON_EXE}"
    )

    return spark


# ============================================================
# VALIDATE SP3 PARQUET EXISTS
# ============================================================

def validate_sp3_parquet_exists():

    print()
    print("[2] Checking SP3 Parquet input...")
    print("-" * 75)

    if not os.path.exists(SP3_OUTPUT_DIR):

        raise FileNotFoundError(
            "SP3 Parquet output directory does not exist:\n"
            f"{SP3_OUTPUT_DIR}\n\n"
            "Run SP3 first."
        )

    parquet_files = []

    for root, dirs, files in os.walk(
        SP3_OUTPUT_DIR
    ):

        for filename in files:

            if filename.lower().endswith(
                ".parquet"
            ):

                parquet_files.append(
                    os.path.join(
                        root,
                        filename
                    )
                )

    if not parquet_files:

        raise FileNotFoundError(
            "No Parquet files found in SP3 output:\n"
            f"{SP3_OUTPUT_DIR}"
        )

    print(
        f"SP3 Parquet directory : "
        f"{SP3_OUTPUT_DIR}"
    )

    print(
        f"Parquet files found   : "
        f"{len(parquet_files)}"
    )

    for path in parquet_files[:10]:

        print(
            f"  - {os.path.basename(path)}"
        )

    if len(parquet_files) > 10:

        print(
            f"  ... and "
            f"{len(parquet_files) - 10} more"
        )

    print()
    print(
        "SP3 Parquet input: PASS"
    )

    return parquet_files


# ============================================================
# LOAD SP3 PARQUET
# ============================================================

def load_sp3(spark):

    print()
    print(
        "[3] Reading verified SP3 Parquet..."
    )
    print("-" * 75)

    validate_sp3_parquet_exists()

    activity_df = (
        spark.read
        .parquet(
            SP3_OUTPUT_DIR
        )
    )

    row_count = activity_df.count()

    print(
        f"SP3 rows read       : "
        f"{row_count:,}"
    )

    print(
        f"SP3 columns         : "
        f"{len(activity_df.columns)}"
    )

    if row_count == 0:

        raise ValueError(
            "SP3 Parquet contains zero rows."
        )

    print()
    print("SP3 schema:")

    activity_df.printSchema()

    print()
    print(
        "SP3 Parquet loaded successfully."
    )

    return activity_df


# ============================================================
# VALIDATE SP3 INPUT
# ============================================================

def validate_sp3_input(df):

    print()
    print(
        "[4] Validating SP3 input..."
    )
    print("-" * 75)

    # --------------------------------------------------------
    # Required columns
    # --------------------------------------------------------

    missing = [

        column

        for column in REQUIRED_SP3_COLUMNS

        if column not in df.columns
    ]

    if missing:

        raise ValueError(
            "SP3 is missing required columns:\n"
            + "\n".join(
                f"  - {column}"
                for column in missing
            )
        )

    print(
        "Required column validation: PASS"
    )

    # --------------------------------------------------------
    # Row count
    # --------------------------------------------------------

    row_count = df.count()

    print(
        f"SP3 rows received : "
        f"{row_count:,}"
    )

    if row_count == 0:

        raise ValueError(
            "SP3 contains zero rows."
        )

    # --------------------------------------------------------
    # Country code must already be removed by SP3
    # --------------------------------------------------------

    if "country_code" in df.columns:

        raise ValueError(
            "country_code must not exist "
            "in SP3 output."
        )

    print(
        "country_code removal validation: PASS"
    )

    # --------------------------------------------------------
    # SP3 grain
    # --------------------------------------------------------

    duplicate_count = (

        df

        .groupBy(
            "timestamp",
            "grid_id"
        )

        .count()

        .filter(
            F.col("count") > 1
        )

        .count()
    )

    print(
        f"Duplicate timestamp + grid_id groups : "
        f"{duplicate_count}"
    )

    if duplicate_count != 0:

        raise ValueError(
            "SP3 grain validation failed. "
            "Duplicate timestamp + grid_id "
            "groups detected."
        )

    print(
        "SP3 grain validation: PASS"
    )

    print(
        "SP3 grain = timestamp + grid_id"
    )

    return row_count


# ============================================================
# SP3 TEMPORAL VALIDATION
# ============================================================

def validate_sp3_temporal_coverage(df):

    print()
    print(
        "[5] Validating SP3 temporal coverage..."
    )
    print("-" * 75)

    distinct_dates = (

        df

        .select("date")

        .distinct()

        .count()
    )

    distinct_hours = (

        df

        .select("hour")

        .distinct()

        .count()
    )

    distinct_timestamps = (

        df

        .select("timestamp")

        .distinct()

        .count()
    )

    print(
        f"Distinct dates       : "
        f"{distinct_dates}"
    )

    print(
        f"Distinct hours       : "
        f"{distinct_hours}"
    )

    print(
        f"Distinct timestamps  : "
        f"{distinct_timestamps}"
    )

    # --------------------------------------------------------
    # SP3 should contain 7 days × 24 hours
    # --------------------------------------------------------

    expected_timestamps = 7 * 24

    if distinct_timestamps != expected_timestamps:

        raise ValueError(
            "SP3 temporal validation failed. "
            f"Expected {expected_timestamps} distinct "
            f"hourly timestamps but found "
            f"{distinct_timestamps}."
        )

    if distinct_dates != 7:

        raise ValueError(
            "SP3 temporal validation failed. "
            f"Expected 7 distinct dates but found "
            f"{distinct_dates}."
        )

    if distinct_hours != 24:

        raise ValueError(
            "SP3 temporal validation failed. "
            f"Expected 24 distinct hours but found "
            f"{distinct_hours}."
        )

    print()
    print(
        "Temporal coverage validation: PASS"
    )

    return distinct_timestamps


# ============================================================
# INSPECT GEOJSON
# ============================================================

def inspect_geojson():

    print()
    print(
        "[6] Inspecting Milan GeoJSON..."
    )
    print("-" * 75)

    if not os.path.exists(
        GEOJSON_PATH
    ):

        raise FileNotFoundError(
            "GeoJSON not found:\n"
            f"{GEOJSON_PATH}"
        )

    print(
        f"GeoJSON path: "
        f"{GEOJSON_PATH}"
    )

    with open(
        GEOJSON_PATH,
        "r",
        encoding="utf-8"
    ) as file:

        geojson = json.load(file)

    top_level_type = (
        geojson.get("type")
    )

    print(
        f"Top-level type: "
        f"{top_level_type}"
    )

    if top_level_type != "FeatureCollection":

        raise ValueError(
            "Expected GeoJSON FeatureCollection, "
            f"got {top_level_type}"
        )

    features = geojson.get(
        "features",
        []
    )

    print(
        f"Feature count: "
        f"{len(features):,}"
    )

    if not features:

        raise ValueError(
            "GeoJSON contains no features."
        )

    if len(features) != EXPECTED_GRID_CELLS:

        raise ValueError(
            "Unexpected GeoJSON feature count. "
            f"Expected {EXPECTED_GRID_CELLS:,}, "
            f"found {len(features):,}."
        )

    # --------------------------------------------------------
    # Inspect first feature
    # --------------------------------------------------------

    first_feature = features[0]

    print()
    print(
        "First feature structure:"
    )

    print(
        f"  Feature type : "
        f"{first_feature.get('type')}"
    )

    print(
        f"  Top-level id : "
        f"{first_feature.get('id')}"
    )

    properties = first_feature.get(
        "properties",
        {}
    )

    print(
        f"  Properties keys: "
        f"{list(properties.keys())}"
    )

    print(
        f"  properties.cellId : "
        f"{properties.get('cellId')}"
    )

    geometry = first_feature.get(
        "geometry",
        {}
    )

    print(
        f"  Geometry type : "
        f"{geometry.get('type')}"
    )

    if "cellId" not in properties:

        raise ValueError(
            "GeoJSON feature does not contain "
            "properties.cellId."
        )

    print()
    print(
        "IMPORTANT JOIN RULE:"
    )

    print(
        "GeoJSON properties.cellId "
        "-> project grid_id"
    )

    print(
        "DO NOT use feature['id']; "
        "it is 0-based."
    )

    return geojson


# ============================================================
# BUILD GRID LOOKUP
# ============================================================

def build_grid_lookup(
    spark,
    geojson
):

    print()
    print(
        "[7] Building Spark grid lookup..."
    )
    print("-" * 75)

    features = geojson.get(
        "features",
        []
    )

    if not features:

        raise ValueError(
            "GeoJSON contains no features."
        )

    # --------------------------------------------------------
    # Validate GeoJSON keys in Python
    # --------------------------------------------------------

    seen_ids = set()

    for feature in features:

        properties = feature.get(
            "properties",
            {}
        )

        cell_id = properties.get(
            "cellId"
        )

        if cell_id is None:

            raise ValueError(
                "Found GeoJSON feature without "
                "properties.cellId."
            )

        try:

            grid_id = int(
                cell_id
            )

        except (
            TypeError,
            ValueError
        ):

            raise ValueError(
                f"Invalid properties.cellId: "
                f"{cell_id}"
            )

        if grid_id in seen_ids:

            raise ValueError(
                f"Duplicate properties.cellId "
                f"found: {grid_id}"
            )

        seen_ids.add(
            grid_id
        )

        if feature.get(
            "geometry"
        ) is None:

            raise ValueError(
                f"Feature {grid_id} has no geometry."
            )

    print(
        f"Validated GeoJSON features: "
        f"{len(features):,}"
    )

    print(
        "Join key: properties.cellId"
    )

    # --------------------------------------------------------
    # Read GeoJSON directly through Spark
    # --------------------------------------------------------

    raw_geojson_df = (

        spark.read

        .option(
            "multiLine",
            "true"
        )

        .json(
            GEOJSON_PATH
        )
    )

    grid_lookup_df = (

        raw_geojson_df

        .select(
            F.explode(
                "features"
            ).alias(
                "feature"
            )
        )

        .select(

            F.col(
                "feature.properties.cellId"
            )
            .cast("long")
            .alias(
                "grid_id"
            ),

            F.to_json(
                F.col(
                    "feature.geometry"
                )
            )
            .alias(
                "geometry"
            )
        )

        .filter(

            F.col(
                "grid_id"
            ).isNotNull()

            &

            F.col(
                "geometry"
            ).isNotNull()
        )
    )

    lookup_count = (
        grid_lookup_df.count()
    )

    print(
        f"Grid lookup rows: "
        f"{lookup_count:,}"
    )

    print(
        f"Expected reference grid cells: "
        f"{EXPECTED_GRID_CELLS:,}"
    )

    if lookup_count != len(features):

        raise ValueError(
            "Grid lookup row count does not "
            "match GeoJSON feature count. "
            f"features={len(features):,}, "
            f"lookup={lookup_count:,}"
        )

    # --------------------------------------------------------
    # Duplicate grid IDs
    # --------------------------------------------------------

    duplicate_grid_ids = (

        grid_lookup_df

        .groupBy(
            "grid_id"
        )

        .count()

        .filter(
            F.col("count") > 1
        )

        .count()
    )

    print(
        f"Duplicate grid_id values in lookup: "
        f"{duplicate_grid_ids}"
    )

    if duplicate_grid_ids != 0:

        raise ValueError(
            "GeoJSON lookup contains duplicate "
            "grid_id values."
        )

    # --------------------------------------------------------
    # NULL grid IDs
    # --------------------------------------------------------

    null_grid_ids = (

        grid_lookup_df

        .filter(
            F.col("grid_id").isNull()
        )

        .count()
    )

    print(
        f"NULL grid_id values in lookup: "
        f"{null_grid_ids}"
    )

    if null_grid_ids != 0:

        raise ValueError(
            "GeoJSON lookup contains NULL grid_id values."
        )

    print(
        "Grid lookup validation: PASS"
    )

    return grid_lookup_df


# ============================================================
# GEOJSON GRID ID RANGE VALIDATION
# ============================================================

def validate_grid_ids(
    grid_lookup_df
):

    print()
    print(
        "[8] Validating GeoJSON grid identifiers..."
    )
    print("-" * 75)

    result = (

        grid_lookup_df

        .agg(

            F.min(
                "grid_id"
            ).alias(
                "min_grid"
            ),

            F.max(
                "grid_id"
            ).alias(
                "max_grid"
            ),

            F.countDistinct(
                "grid_id"
            ).alias(
                "distinct_grid_ids"
            )
        )

        .first()
    )

    min_grid = result["min_grid"]
    max_grid = result["max_grid"]
    distinct_grid_ids = result[
        "distinct_grid_ids"
    ]

    print(
        f"Minimum grid_id       : "
        f"{min_grid}"
    )

    print(
        f"Maximum grid_id       : "
        f"{max_grid}"
    )

    print(
        f"Distinct grid IDs     : "
        f"{distinct_grid_ids:,}"
    )

    if (
        min_grid != 1
        or
        max_grid != EXPECTED_GRID_CELLS
        or
        distinct_grid_ids != EXPECTED_GRID_CELLS
    ):

        raise ValueError(
            "GeoJSON grid ID validation failed. "
            "Expected unique grid IDs 1-10000."
        )

    print(
        "Grid ID range validation: PASS"
    )


# ============================================================
# COMPARE JOIN PLANS
# ============================================================

def compare_join_plans(
    activity_df,
    grid_lookup_df
):

    print()
    print(
        "[9] Comparing standard join and broadcast join..."
    )
    print("-" * 75)

    print()
    print(
        "STANDARD JOIN PLAN"
    )

    print(
        "-" * 40
    )

    standard_join = (

        activity_df

        .join(

            grid_lookup_df,

            on="grid_id",

            how="left"
        )
    )

    standard_join.explain(
        "formatted"
    )

    print()
    print(
        "BROADCAST JOIN PLAN"
    )

    print(
        "-" * 40
    )

    broadcast_join = (

        activity_df

        .join(

            broadcast(
                grid_lookup_df
            ),

            on="grid_id",

            how="left"
        )
    )

    broadcast_join.explain(
        "formatted"
    )

    print()
    print(
        "Why broadcast is appropriate:"
    )

    print(
        "The activity DataFrame contains "
        "millions of rows, while the Milan "
        "grid reference contains only "
        "10,000 rows."
    )

    print(
        "The small static lookup can be "
        "broadcast to Spark executors, "
        "avoiding a large shuffle of the "
        "activity dataset."
    )


# ============================================================
# PERFORM LEFT JOIN
# ============================================================

def enrich_activity(
    activity_df,
    grid_lookup_df
):

    print()
    print(
        "[10] Performing geospatial enrichment..."
    )
    print("-" * 75)

    before_count = (
        activity_df.count()
    )

    print(
        f"Activity rows before join: "
        f"{before_count:,}"
    )

    print()
    print(
        "JOIN:"
    )

    print(
        "  activity.grid_id"
    )

    print(
        "      LEFT JOIN"
    )

    print(
        "  grid_lookup.grid_id"
    )

    grid_activity_geo_df = (

        activity_df

        .join(

            broadcast(
                grid_lookup_df
            ),

            on="grid_id",

            how="left"
        )
    )

    after_count = (
        grid_activity_geo_df.count()
    )

    print(
        f"Activity rows after join : "
        f"{after_count:,}"
    )

    if after_count != before_count:

        raise ValueError(
            "Row-count validation failed. "
            "The left join changed the row count. "
            "This indicates duplicate grid_id "
            "values in the lookup."
        )

    print(
        "Row-count preservation: PASS"
    )

    return grid_activity_geo_df


# ============================================================
# ENRICHMENT COVERAGE
# ============================================================

def validate_enrichment(
    activity_df,
    enriched_df
):

    print()
    print(
        "[11] Validating enrichment coverage..."
    )
    print("-" * 75)

    activity_grid_count = (

        activity_df

        .select(
            "grid_id"
        )

        .distinct()

        .count()
    )

    print(
        f"Distinct activity grids : "
        f"{activity_grid_count:,}"
    )

    matched_grids = (

        enriched_df

        .filter(
            F.col(
                "geometry"
            ).isNotNull()
        )

        .select(
            "grid_id"
        )

        .distinct()

        .count()
    )

    missing_grids = (

        enriched_df

        .filter(
            F.col(
                "geometry"
            ).isNull()
        )

        .select(
            "grid_id"
        )

        .distinct()
    )

    missing_grid_count = (
        missing_grids.count()
    )

    print(
        f"Matched grids            : "
        f"{matched_grids:,}"
    )

    print(
        f"Unmatched grids          : "
        f"{missing_grid_count:,}"
    )

    if activity_grid_count == 0:

        coverage = 0.0

    else:

        coverage = (

            matched_grids
            /
            activity_grid_count

        ) * 100

    print(
        f"Enrichment coverage      : "
        f"{coverage:.2f}%"
    )

    # --------------------------------------------------------
    # Unmatched IDs
    # --------------------------------------------------------

    print()
    print(
        "Unmatched grid_id values:"
    )

    print(
        "-" * 40
    )

    unmatched_ids = [

        row["grid_id"]

        for row in (

            missing_grids

            .orderBy(
                "grid_id"
            )

            .collect()
        )
    ]

    if unmatched_ids:

        print(
            unmatched_ids
        )

    else:

        print(
            "[]"
        )

    if coverage != 100.0:

        raise ValueError(
            f"Enrichment coverage is "
            f"{coverage:.2f}%. "
            "Expected 100%."
        )

    print()
    print(
        "Enrichment coverage: PASS"
    )

    print(
        "100% of observed grid_id values "
        "have geometry."
    )

    return unmatched_ids


# ============================================================
# FINAL SP4 SCHEMA
# ============================================================

def prepare_final_schema(
    enriched_df
):

    print()
    print(
        "[12] Preparing final SP4 schema..."
    )
    print("-" * 75)

    required_output = [

        "timestamp",
        "grid_id",

        "sms_in",
        "sms_out",

        "call_in",
        "call_out",

        "internet_activity",

        "total_activity",

        "geometry",
    ]

    missing = [

        column

        for column in required_output

        if column not in enriched_df.columns
    ]

    if missing:

        raise ValueError(
            "Missing required SP4 output columns: "
            f"{missing}"
        )

    final_df = (

        enriched_df

        .select(
            *required_output
        )
    )

    print()
    print(
        "Final SP4 columns:"
    )

    for column in final_df.columns:

        print(
            f"  - {column}"
        )

    return final_df


# ============================================================
# POLYGON CENTROID
# ============================================================

def polygon_centroid(
    ring
):

    if not ring or len(ring) < 3:

        return None

    points = [

        (
            float(point[0]),
            float(point[1])
        )

        for point in ring

        if len(point) >= 2
    ]

    if len(points) < 3:

        return None

    if points[0] == points[-1]:

        points = points[:-1]

    if len(points) < 3:

        return None

    area_twice = 0.0

    cx = 0.0

    cy = 0.0

    n = len(points)

    for i in range(n):

        x1, y1 = points[i]

        x2, y2 = points[
            (i + 1) % n
        ]

        cross = (
            x1 * y2
            -
            x2 * y1
        )

        area_twice += cross

        cx += (
            x1 + x2
        ) * cross

        cy += (
            y1 + y2
        ) * cross

    if abs(area_twice) < 1e-12:

        avg_lon = (

            sum(
                p[0]
                for p in points
            )
            /
            len(points)
        )

        avg_lat = (

            sum(
                p[1]
                for p in points
            )
            /
            len(points)
        )

        return (
            avg_lon,
            avg_lat
        )

    cx /= (
        3.0 * area_twice
    )

    cy /= (
        3.0 * area_twice
    )

    return (
        cx,
        cy
    )


# ============================================================
# GEOMETRY CENTROID
# ============================================================

def geometry_centroid(
    geometry
):

    if not geometry:

        return None

    geometry_type = (
        geometry.get(
            "type"
        )
    )

    coordinates = (
        geometry.get(
            "coordinates"
        )
    )

    if not coordinates:

        return None

    # --------------------------------------------------------
    # Polygon
    # --------------------------------------------------------

    if geometry_type == "Polygon":

        outer_ring = coordinates[0]

        return polygon_centroid(
            outer_ring
        )

    # --------------------------------------------------------
    # MultiPolygon
    # --------------------------------------------------------

    if geometry_type == "MultiPolygon":

        centroids = []

        for polygon in coordinates:

            if not polygon:

                continue

            centroid = polygon_centroid(
                polygon[0]
            )

            if centroid:

                centroids.append(
                    centroid
                )

        if not centroids:

            return None

        lon = (

            sum(
                c[0]
                for c in centroids
            )
            /
            len(centroids)
        )

        lat = (

            sum(
                c[1]
                for c in centroids
            )
            /
            len(centroids)
        )

        return (
            lon,
            lat
        )

    return None


# ============================================================
# GEOGRAPHIC SPOT CHECK
# ============================================================

def geographic_spot_check(
    grid_lookup_df
):

    print()
    print(
        "[13] Geographic spot-check..."
    )
    print("-" * 75)

    check_ids = [
        1,
        2,
        4821
    ]

    rows = (

        grid_lookup_df

        .filter(
            F.col(
                "grid_id"
            ).isin(
                check_ids
            )
        )

        .select(
            "grid_id",
            "geometry"
        )

        .orderBy(
            "grid_id"
        )

        .collect()
    )

    centroid_results = {}

    for row in rows:

        grid_id = row[
            "grid_id"
        ]

        geometry = json.loads(
            row[
                "geometry"
            ]
        )

        centroid = geometry_centroid(
            geometry
        )

        if centroid is None:

            print(
                f"Grid {grid_id}: "
                "centroid could not be calculated"
            )

            continue

        longitude, latitude = centroid

        centroid_results[
            grid_id
        ] = (
            longitude,
            latitude
        )

        print(
            f"grid_id={grid_id:4d} | "
            f"longitude={longitude:.6f} | "
            f"latitude={latitude:.6f}"
        )

    for grid_id in check_ids:

        if grid_id not in centroid_results:

            raise ValueError(
                "Could not calculate centroid "
                f"for grid_id {grid_id}"
            )

    # --------------------------------------------------------
    # Grid 1 vs Grid 2
    # --------------------------------------------------------

    lon1, lat1 = centroid_results[1]

    lon2, lat2 = centroid_results[2]

    distance = math.sqrt(

        (lon1 - lon2) ** 2

        +

        (lat1 - lat2) ** 2
    )

    print()

    print(
        f"Grid 1 -> Grid 2 centroid distance: "
        f"{distance:.8f}"
    )

    if distance <= 0:

        raise ValueError(
            "Grid 1 and Grid 2 have "
            "identical centroids."
        )

    print(
        "Grid 1 / Grid 2 adjacency sanity check: PASS"
    )

    # --------------------------------------------------------
    # Milan bounding box
    # --------------------------------------------------------

    lon4821, lat4821 = (
        centroid_results[4821]
    )

    in_milan_bbox = (

        8.8 <= lon4821 <= 9.6

        and

        45.2 <= lat4821 <= 45.8
    )

    print(
        f"Grid 4821 inside Milan bounding box: "
        f"{in_milan_bbox}"
    )

    if not in_milan_bbox:

        raise ValueError(
            "Grid 4821 centroid is outside "
            "the expected Milan bounding box."
        )

    print(
        "Geographic spot-check: PASS"
    )


# ============================================================
# TOP HIGH-ACTIVITY GRIDS
# ============================================================

def show_top_activity_grids(
    enriched_df
):

    print()
    print(
        "[14] Top high-activity grids..."
    )
    print("-" * 75)

    top_grids = (

        enriched_df

        .groupBy(
            "grid_id"
        )

        .agg(

            F.sum(
                "total_activity"
            ).alias(
                "window_total_activity"
            ),

            F.first(
                "geometry"
            ).alias(
                "geometry"
            )
        )

        .orderBy(
            F.desc(
                "window_total_activity"
            )
        )

        .limit(10)
    )

    print()
    print(
        "Top 10 grids by total activity:"
    )

    top_grids.select(

        "grid_id",

        "window_total_activity"

    ).show(
        10,
        truncate=False
    )

    print(
        "Top 10 high-activity grids retained "
        "with geometry."
    )

    return top_grids


# ============================================================
# FINAL VALIDATION
# ============================================================

def final_validation(
    activity_df,
    final_df
):

    print()
    print(
        "[15] Final SP4 validation..."
    )
    print("-" * 75)

    input_count = (
        activity_df.count()
    )

    output_count = (
        final_df.count()
    )

    print(
        f"SP3 input rows : "
        f"{input_count:,}"
    )

    print(
        f"SP4 output rows: "
        f"{output_count:,}"
    )

    # --------------------------------------------------------
    # Row count
    # --------------------------------------------------------

    if input_count != output_count:

        raise ValueError(
            "SP4 row count does not equal "
            "SP3 row count."
        )

    print(
        "Row-count preservation: PASS"
    )

    # --------------------------------------------------------
    # Duplicate grain
    # --------------------------------------------------------

    duplicate_count = (

        final_df

        .groupBy(
            "timestamp",
            "grid_id"
        )

        .count()

        .filter(
            F.col("count") > 1
        )

        .count()
    )

    print(
        f"Duplicate timestamp + grid_id groups: "
        f"{duplicate_count}"
    )

    if duplicate_count != 0:

        raise ValueError(
            "SP4 contains duplicate "
            "timestamp + grid_id rows."
        )

    print(
        "Duplicate validation: PASS"
    )

    # --------------------------------------------------------
    # NULL geometry
    # --------------------------------------------------------

    missing_geometry = (

        final_df

        .filter(
            F.col(
                "geometry"
            ).isNull()
        )

        .count()
    )

    print(
        f"Rows with missing geometry: "
        f"{missing_geometry}"
    )

    if missing_geometry != 0:

        raise ValueError(
            "Some activity rows have "
            "missing geometry."
        )

    print(
        "Geometry validation: PASS"
    )

    # --------------------------------------------------------
    # NULL validation
    # --------------------------------------------------------

    print()
    print(
        "Checking final SP4 NULL values..."
    )

    null_failure = False

    for column in final_df.columns:

        null_count = (

            final_df

            .filter(
                F.col(
                    column
                ).isNull()
            )

            .count()
        )

        print(
            f"{column:<20}: "
            f"{null_count:,}"
        )

        if null_count != 0:

            null_failure = True

    if null_failure:

        raise ValueError(
            "SP4 contains NULL values."
        )

    print(
        "Final NULL validation: PASS"
    )

    # --------------------------------------------------------
    # Final sample
    # --------------------------------------------------------

    print()
    print(
        "Sample enriched records:"
    )

    print(
        "-" * 75
    )

    final_df.select(

        "timestamp",
        "grid_id",

        "sms_in",
        "sms_out",

        "call_in",
        "call_out",

        "internet_activity",

        "total_activity",

        "geometry"

    ).show(
        5,
        truncate=80
    )


# ============================================================
# WRITE SP4 PARQUET
# ============================================================

def write_sp4_output(
    df
):

    output_dir = os.path.join(
        BASE_DIR,
        "data",
        "processed",
        "sp4_geo_enriched"
    )

    print()
    print(
        "[16] Writing SP4 output to Parquet..."
    )
    print("-" * 75)

    print(
        f"Output location: "
        f"{output_dir}"
    )

    (
        df

        .write

        .mode(
            "overwrite"
        )

        .option(
            "compression",
            "snappy"
        )

        .parquet(
            output_dir
        )
    )

    print()
    print(
        "SP4 Parquet write: PASS"
    )

    return output_dir


# ============================================================
# VERIFY SP4 PARQUET
# ============================================================

def verify_sp4_output(
    spark,
    output_dir,
    expected_rows
):

    print()
    print(
        "[17] Verifying SP4 Parquet output..."
    )
    print("-" * 75)

    if not os.path.exists(
        output_dir
    ):

        raise FileNotFoundError(
            "SP4 Parquet output was not created:\n"
            f"{output_dir}"
        )

    parquet_files = []

    for root, dirs, files in os.walk(
        output_dir
    ):

        for filename in files:

            if filename.lower().endswith(
                ".parquet"
            ):

                parquet_files.append(
                    os.path.join(
                        root,
                        filename
                    )
                )

    print(
        f"Parquet files found: "
        f"{len(parquet_files)}"
    )

    if not parquet_files:

        raise ValueError(
            "No Parquet files found "
            "in SP4 output."
        )

    verified_df = (

        spark.read

        .parquet(
            output_dir
        )
    )

    actual_rows = (
        verified_df.count()
    )

    print(
        f"Rows read back from Parquet: "
        f"{actual_rows:,}"
    )

    if actual_rows != expected_rows:

        raise ValueError(
            "SP4 Parquet row-count "
            "verification failed. "
            f"Expected {expected_rows:,}, "
            f"found {actual_rows:,}."
        )

    # --------------------------------------------------------
    # Required schema
    # --------------------------------------------------------

    expected_columns = [

        "timestamp",
        "grid_id",

        "sms_in",
        "sms_out",

        "call_in",
        "call_out",

        "internet_activity",

        "total_activity",

        "geometry",
    ]

    if verified_df.columns != expected_columns:

        raise ValueError(
            "SP4 Parquet schema mismatch.\n"
            f"Expected: {expected_columns}\n"
            f"Found: {verified_df.columns}"
        )

    # --------------------------------------------------------
    # Geometry validation
    # --------------------------------------------------------

    null_geometry = (

        verified_df

        .filter(
            F.col(
                "geometry"
            ).isNull()
        )

        .count()
    )

    if null_geometry != 0:

        raise ValueError(
            "SP4 Parquet contains "
            "NULL geometry values."
        )

    print()
    print(
        "Verified SP4 Parquet schema:"
    )

    verified_df.printSchema()

    print()
    print(
        "SP4 Parquet verification: PASS"
    )

    return verified_df


# ============================================================
# MAIN SP4
# ============================================================

def run_sp4():

    spark = None

    try:

        spark = create_spark_session()

        print()
        print("=" * 75)
        print(
            "SP4 - MILAN TELECOM GEOSPATIAL ENRICHMENT"
        )
        print("=" * 75)

        # ====================================================
        # SP3 PARQUET
        # ====================================================

        activity_df = load_sp3(
            spark
        )

        sp3_rows = validate_sp3_input(
            activity_df
        )

        validate_sp3_temporal_coverage(
            activity_df
        )

        # ====================================================
        # GEOJSON
        # ====================================================

        geojson = inspect_geojson()

        grid_lookup_df = build_grid_lookup(
            spark,
            geojson
        )

        validate_grid_ids(
            grid_lookup_df
        )

        # ====================================================
        # JOIN PLAN
        # ====================================================

        compare_join_plans(
            activity_df,
            grid_lookup_df
        )

        # ====================================================
        # GEO ENRICHMENT
        # ====================================================

        enriched_df = enrich_activity(
            activity_df,
            grid_lookup_df
        )

        # ====================================================
        # COVERAGE
        # ====================================================

        validate_enrichment(
            activity_df,
            enriched_df
        )

        # ====================================================
        # FINAL SCHEMA
        # ====================================================

        grid_activity_geo_df = (
            prepare_final_schema(
                enriched_df
            )
        )

        # ====================================================
        # GEOGRAPHIC VALIDATION
        # ====================================================

        geographic_spot_check(
            grid_lookup_df
        )

        # ====================================================
        # TOP ACTIVITY
        # ====================================================

        top_grids_df = (
            show_top_activity_grids(
                grid_activity_geo_df
            )
        )

        # Prevent unused-variable warning in some environments.
        _ = top_grids_df

        # ====================================================
        # CACHE
        # ====================================================

        grid_activity_geo_df.cache()

        final_count = (
            grid_activity_geo_df.count()
        )

        # ====================================================
        # FINAL VALIDATION
        # ====================================================

        final_validation(
            activity_df,
            grid_activity_geo_df
        )

        # ====================================================
        # WRITE OUTPUT
        # ====================================================

        sp4_output_dir = write_sp4_output(
            grid_activity_geo_df
        )

        # ====================================================
        # VERIFY OUTPUT
        # ====================================================

        verified_df = verify_sp4_output(

            spark,

            sp4_output_dir,

            final_count
        )

        # ====================================================
        # SUCCESS
        # ====================================================

        print()
        print("=" * 75)
        print(
            "SP4 GEOSPATIAL ENRICHMENT "
            "COMPLETED SUCCESSFULLY"
        )
        print("=" * 75)

        print(
            f"SP3 input rows       : "
            f"{sp3_rows:,}"
        )

        print(
            f"SP4 output rows      : "
            f"{final_count:,}"
        )

        print(
            "Input source         : "
            "SP3 Parquet"
        )

        print(
            f"SP3 input location   : "
            f"{SP3_OUTPUT_DIR}"
        )

        print(
            "Join type             : "
            "LEFT JOIN"
        )

        print(
            "Join key              : "
            "grid_id = properties.cellId"
        )

        print(
            "GeoJSON feature count : "
            f"{len(geojson['features']):,}"
        )

        print(
            "Geometry              : "
            "Polygon / GeoJSON"
        )

        print(
            "Enrichment coverage   : "
            "100%"
        )

        print(
            "Unmatched grids       : "
            "0"
        )

        print(
            "Duplicate grain       : "
            "0"
        )

        print(
            "Row count preserved   : "
            "YES"
        )

        print(
            "Output format         : "
            "Parquet"
        )

        print(
            f"Output location       : "
            f"{sp4_output_dir}"
        )

        print(
            "Parquet verification  : "
            "PASS"
        )

        print(
            "Status                : "
            "SUCCESS"
        )

        print("=" * 75)

        return verified_df

    except Exception as e:

        print()
        print("=" * 75)
        print(
            "SP4 FAILED"
        )
        print("=" * 75)

        print(
            f"Error: "
            f"{type(e).__name__}: {e}"
        )

        raise

    finally:

        if spark is not None:

            try:

                spark.stop()

            except Exception:

                pass


# ============================================================
# SCRIPT ENTRY POINT
# ============================================================

if __name__ == "__main__":

    run_sp4()